#!/usr/local/bin/perl -w

use strict;
use warnings;
use Chisel::SanityCheck qw/:all/;

my %files = args();

check_files(
    files => \%files,
    min   => [qw/ MAIN /],
    max   => [qw/ MAIN blacklist /],
);

# disallow zero-length file
my $sudoers_contents = read_file( filename => $files{MAIN} );
if( ! $sudoers_contents ) {
    die "zero-length sudoers file\n";
}

# sudoers syntax check
my $visudo;

if( -x "/usr/local/sbin/visudo" ) {
    $visudo = "/usr/local/sbin/visudo";
}
else {
    $visudo = "/usr/sbin/visudo";
}

my $rc = system( $visudo, "-cf", $files{MAIN} );

if( $rc == 0 ) {
    exit 0;
} else {
    die "[FAILED] visudo -cf $files{MAIN}\n$sudoers_contents";
}
